// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatTreeNode } from "./ChatTreeNode";

export type ChatTreeProjection = { version: number, revision: bigint, currentNodeId: string | null, visibleNodeIds: Array<string>, visibleTurnIds: Array<string>, nodes: Array<ChatTreeNode>, };
