// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatTreeNodeStatus } from "./ChatTreeNodeStatus";

export type ChatTreeNode = { nodeId: string, parentNodeId: string | null, turnId: string | null, order: bigint, status: ChatTreeNodeStatus, summary: string | null, };
